name: 1. Scheduler for Cron Jobs
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  run_cron_job:
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: echo "This is a scheduled job running every 5 minutes."