name: 2. Job Concurrency

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building..."
      - name : sleep 10 seconds
        run: sleep 10

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test
        run: echo "Testing..."

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    concurrency:
      group: deploy-job
      cancel-in-progress: true
    steps:
      - name: Deploy
        run: echo "Deploying..."
      - name : sleep 10 seconds
        run: sleep 600s