name: test workflow dispatch

on:
  workflow_dispatch:
    inputs:
      workflow_id:
        description: "The ID of the workflow to download"
        required: true
      output_file:
        description: "The name of the output file"
        required: true
    
jobs:
    download-file:
        runs-on: ubuntu-latest
    
        env:
            WORKFLOW_ID: ${{ inputs.workflow_id }}
            OUTPUT_FILE: ${{ inputs.output_file }}
    
        steps:
        - name: Display Inputs
          run: |
            echo "Workflow ID: $WORKFLOW_ID"
            echo "Output File: $OUTPUT_FILE"
    
        - name: Create Output File
          run: |
            echo "This is the output file for workflow ID $WORKFLOW_ID" > $OUTPUT_FILE
            echo "✅ Output file created successfully"