name: my workflow
on:
  push:
    branches:
      - main
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: Run a script
            run: echo "Hello, world!"
          - name: create file
            run: echo "This is a sample file." > ex.txt
          - name: read file
            run: cat ex.txt 