name: genarate multiple jobs
on:
    workflow_dispatch: 

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
            - name: Install cosway program
              run: sudo apt-get install cowsay -y
            - name: Execute cosway CMD
              run: cowsay -f dragon "Run For Cover, I am a Dragon" >> dragon.txt
            - name: Upload File
              uses: actions/upload-artifact@v4
              with:
                name: dragon-file
                path: dragon.txt

    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:
            - name: Sleep for 10 seconds
              run: sleep 10
            - name: Download File
              uses: actions/download-artifact@v4
              with:
                name: dragon-file
            - name: Test File Exist
              run: grep -i "dragon" dragon.txt
    
    deploy_job:
        concurrency:
            group: prod-deploy-job
            cancel-in-progress: false
        needs: [test_job]
        runs-on: ubuntu-latest
        steps:
            - name: Download File
              uses: actions/download-artifact@v4
              with:
                name: dragon-file
            - name: Read File
              run: cat dragon.txt
            - name: Display
              run: echo "This is a test file"