name: genarate sh scripts
on:
  push:
    branches:
      - main
jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Make run.sh executable
            run: chmod +x ./run.sh
          - name: read sh file
            run: ./run.sh