name: My test on GitHub Actions

on:
    push:
        branches:
            - test

jobs:
    download-file:
        runs-on: ubuntu-latest
    
        env:
            WORKFLOW_ID: ${{ inputs.workflow_id }}
            OUTPUT_FILE: ${{ inputs.output_file }}
            OUTPUT_FILE_NUMBER: ${{ inputs.output_file_number }}
    
        steps:
        - name: Display Inputs
          run: |
            echo "Workflow ID: $WORKFLOW_ID"
            echo "Output File: $OUTPUT_FILE"
            echo "Output File Number: $OUTPUT_FILE_NUMBER"
    
        - name: Create Output File
          run: |
            echo "This is output file number $OUTPUT_FILE_NUMBER" > $OUTPUT_FILE
            echo "✅ Output file created successfully"